#!/bin/sh
set -e

echo "----------------------------------------------------------------"
echo " rs-brite installed successfully!"
echo " To enable the daemon for your user, run:"
echo "   systemctl --user daemon-reload"
echo "   systemctl --user enable --now rs-brite"
echo "----------------------------------------------------------------"

exit 0